### PR TITLE
Fixed links in ERCS markdown files

### PR DESCRIPTION
**Pull request by cfries**
The HTML Proofer currently fails because all .md files in ERC reference eip-nnnn.md file but these files have been renamed to erc-nnnn.md. This PR just renames the links in the ERCS md files.
Please check if you find this PR reasonable:

- Replaced (regexp) `\(eip-(\d\d+)\.md\)` by `(erc-$1.md)`
- Replaced (regexp) `\(\./eip-(\d\d+)\.md\)` by `(./erc-$1.md)`
- Replaced (regexp) `\.\./assets/eip-(\d\d+)\/`by `../assets/erc-$1/`
- Replaced (regexp) `\: \./eip-(\d\d+)\.md`by `: ./erc-$1.md`
- Replaced (regexp) `\((\./|\.\./EIPS/)eip-(\d\d+)(\.md|)((#[\w\-]*|))\)` by `(erc-$2$3$4)`
- Replaced (regexp) `\./eip-(\d\d+)\.md` by `./erc-$1.md`

Note: The HTML Proofer will still fail because there are links to EIPs that are no longer in this repository (cross-linking is required). The above will also rename the EIPs to ERCs that are EIPs. Those likely require cross linking as there are no files in the ERCS folder. For those one could consider using abolute links:

- Replaced (regexp) `\(\./(eip|erc)-155(\.md|)(#.*|)\)` by `(https\://eips.ethereum.org/EIPS/eip-155$3)`
- Replaced (regexp) `\(\./(eip|erc)-712(\.md|)(#.*|)\)` by `(https\://eips.ethereum.org/EIPS/eip-712$3)`
- ... and so on for the numbers 86, 101, 170, 658, 1014, 1102, 1153, 1193, 1559, 2255, 2938, 3074, 3085, 3220, 3855, 5069, 5757

(I am using this PR to find our if there is a set of reg exp that will fix all or most of the broken links - I hope you don't mind)

The above regexps reduce the number of errors reported by the HTMLProofer from

```
HTML-Proofer found 1807 failures!
```

to

```
HTML-Proofer found 27 failures!
```

(There is maybe a one regexp for all - the list above is a result from step by step carefully fixing issues)

### CODE REVIEW

**Comment by tbergmueller** [comment]
Thx for doing this @cfries!

**Comment by cfries** [comment]
@lightclient  - I managed to compile a few regexp fixing the links.
- linking to ERCs replaces the local link (eip -> erc).
- linking to EIPs uses an external link to https://eips.ethereum.org/EIPS/eip-712 (with the appropriate number)

I manage to get the broken links down from 1800 to 27. Would it make sense to merge this one now? I could try to fix the others if time permits

(the regexp could be more fancy, but I wanted to go slowly step by step).

**Comment by lightclient** [comment]
Thanks for this @cfries. In general this makes sense, unfortunately it overlooks the issue of building the `eips.ethereum.org` website. That occurs in the `ethereum/eips` repo: 

https://github.com/ethereum/EIPs/blob/25cdf1d059778236e28bf22d752ca48a35af91f6/.github/workflows/jekyll.yml#L46-L57

This PR will cause all the relative ERC links to fail.

**Comment by cfries** [comment]
> https://github.com/ethereum/EIPs/blob/25cdf1d059778236e28bf22d752ca48a35af91f6/.github/workflows/jekyll.yml#L46-L57
> 
> This PR will cause all the relative ERC links to fail.

Thanks for this link. I did not know that. However, if I understand this correctly all relative ERC links will work if there are done via (erc-xxxx.md) or via (./erc-xxxx.md), but they will fail if they are done via (../ERCS/erc-xxxx.md) (which some do, but many don't do). I could modify the regexp - recreating a new PR to standardize the links to be of (./erc-xxxx.md or to refrence ../assets/erc-xxxx. If I unserstand this correctly merging the web pages will then work.

The remaining issues are links from ERC to EIP - these could work realatively after merge but let the validator fail. Two options here:
1. let the validator ignore links to eip
2. use the regexp above to convert all links to eips to absolute paths.

It this correct? If you like I could recreate this PR with modified regexps to at least fix all ERC links in the way above - if this is useful for you.

**Comment by cfries** [comment]
@lightclient How about the following idea:

- Use a set of regexp (as in this PR) to fix all ERC links and replace all EIP links with external links.
- (Optional:) Let the script that performs the merge of the web-site replace the external EIP links with relative links.

Alternatively one could modify the HTMLProofer script to replace links with external ones before doing the proofing, but this solution is a bit strange, because the local markdowns will not render correctly (it has broken links). This makes it harder to check ones markdown before submitting the PR.

Maybe you can discuss this in the meeting and if you like, I could compile the set of useful regexps.

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
Also, please resolve the merge conflicts

**Comment by cfries** [comment]
> Also, please resolve the merge conflicts

Done. Should I try to fix the remaining broken links in other ERCs too? (Not sure if I have enough time for this today).

**Pull request closed without merging**
