### PR TITLE
Update ERC-6734: Move to Review

### PR DESCRIPTION
**Pull request by Therecanbeonlyone1969**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by Therecanbeonlyone1969** [comment]
@SamWilsn I thought the relative link issue for CVEs had been resolved?!

**Comment by SamWilsn** [comment]
That's probably my fault. I'll make sure the linter rules are updated.

**Review by SamWilsn — CHANGES_REQUESTED** [review]
Small nit I can't comment on directly (and please fix before moving into Last Call): you mention "draft standard" when talking about an EIP. That won't make sense when that EIP moves into Final. EIPs should be written as if they were already Final.

---

EIP-3220 is Stagnant. You'll need to either remove links to it, or help push it to Review.

**Comment by Therecanbeonlyone1969** [comment]
> Small nit I can't comment on directly (and please fix before moving into Last Call): you mention "draft standard" when talking about an EIP. That won't make sense when that EIP moves into Final. EIPs should be written as if they were already Final.
> 
> EIP-3220 is Stagnant. You'll need to either remove links to it, or help push it to Review.

Removed mention of EIP-3220

**Review by SamWilsn — COMMENTED** [review]
3220 is still in your `requires` field. You'll either need to remove it or open a pull request moving 3220 to Review.

**Comment by Therecanbeonlyone1969** [comment]
> 3220 is still in your `requires` field. You'll either need to remove it or open a pull request moving 3220 to Review.

Updated `requires` section.

**Review by SamWilsn — APPROVED** [review]

**Pull request merged**
