### PR TITLE
Update ERC-4337: Fix typos

### PR DESCRIPTION
**Pull request by kopy-kat**
Fixing typos

### CODE REVIEW

**Comment by kopy-kat** [comment]
Another thing in the specs that is not entirely clear is whether the following rule gives the account factory and paymaster as an example of an entity that can be staked and thus access their self storage or whether this rule ONLY applies to the factory and paymaster but not any other external contract

https://github.com/ethereum/ERCs/blob/8568c155452785f4de2e30ae665abe5d431281ca/ERCS/erc-4337.md?plain=1#L375C11-L375C11

**Review by drortirosh — APPROVED** [review]

**Comment by drortirosh** [comment]
note that we're in the process of moving the rules from erc4337 itself into
a separate document (erc-7562)

**Comment by drortirosh** [comment]
actually, it is better to re-submit against the version in the eth-infinitism/account-abstraction/erc, as that's what we'll push back into the main ethereum/erc repo.

**Comment by kopy-kat** [comment]
looks like these are already fixed in `/erc` on `develop` branch

**Pull request merged**
