### PR TITLE
Update ERC-4626: replace old repo link

### PR DESCRIPTION
**Pull request by Confucian-e**
Old link is invalid now because author changed file path. I replace that with correct url.

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Comment by Confucian-e** [comment]
@axic, @g11tech, @gcolvin, @lightclient, @SamWilsn, @xinbenlv
 Could you check it out? Opened for a long time.

**Comment by SamWilsn** [comment]
As discussed on EIPIP (ethcatherders/EIPIP#336), we prefer not updating Final proposals.

**Comment by fubuloubu** [comment]
> As discussed on EIPIP (ethcatherders/EIPIP#336), we prefer not updating Final proposals.

Updating a link hardly seems like a substantive change

**Comment by Confucian-e** [comment]
> > As discussed on EIPIP ([ethcatherders/EIPIP#336](https://github.com/ethcatherders/EIPIP/issues/336)), we prefer not updating Final proposals.
> 
> Updating a link hardly seems like a substantive change

Agreed

**Pull request closed without merging**
