### PR TITLE
Add ERC: Cross-Contract Hierarchical NFT

### PR DESCRIPTION
**Pull request by minkyn**
Reopen this ongoing draft from the old [PR](https://github.com/ethereum/EIPs/pull/7638) in repo `EIPs` with all comments addressed.

### CODE REVIEW

**Comment by minkyn** [comment]
@xinbenlv Please take another look. Previous comments include adding a set method and supplementing security considerations.

**Comment by minkyn** [comment]
@SamWilsn Please help with the merge due to this [issue](https://github.com/ethereum/ERCs/issues/110)

**Comment by minkyn** [comment]
How do I request to get approval from @eip-review-bot please?

**Review by xinbenlv — APPROVED** [review]
Retrigger merging

**Comment by minkyn** [comment]
@SamWilsn Sam, can you please help take a look why the bot didn't automatically approve it when all other checks have been satisfied?

**Comment by minkyn** [comment]
image

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Pull request merged**
