### PR TITLE
Update ERC-1: Ethereum Request for Comments Process

### PR DESCRIPTION
**Pull request by Joachim-Lebrun**
see discussions about this here https://ethereum-magicians.org/t/post-eip-erc-split-create-erc-1-an-erc-specific-version-of-eip-1/16301

**Description:**

This pull request introduces ERC-1, a foundational document that outlines the process for Ethereum Request for Comments (ERCs). The creation of ERC-1 is a significant step in formalizing the standards and procedures specific to ERCs, following the recent decision to separate ERCs from EIPs into two distinct repositories.

**Key Highlights:**

1. **Adaptation of EIP-1**: ERC-1 is heavily derived from EIP-1, with necessary modifications to cater specifically to ERCs. This includes changes in terminology, structure, and content to better align with the nature of ERCs.

2. **Open Invitation for Collaboration**: Recognizing the importance of ERC-1 to the Ethereum ecosystem, this PR is not just a submission but an open call for collaboration. The goal is to encourage broad participation from developers, contributors, and stakeholders to refine and enhance this foundational document.

**Why This Matters:**

The introduction of ERC-1 marks a pivotal moment in the evolution of Ethereum's standardization processes. It provides a clear, structured, and community-driven framework for proposing, discussing, and implementing ERCs. This is crucial for fostering innovation, interoperability, and consensus within the Ethereum ecosystem.

**Call for Participation:**

I invite and encourage participation from as many individuals and groups as possible. Your insights, expertise, and feedback are invaluable to ensuring that ERC-1 serves its purpose effectively and inclusively. Whether you're a developer, researcher, implementer, or an enthusiastic community member, your contribution can make a significant difference.

Please review the proposed ERC-1 document, share your thoughts, suggest improvements, and help shape the future of Ethereum Request for Comments.

Together, let's build a robust and collaborative framework for Ethereum's continuous improvement and innovation.

### CODE REVIEW

**Comment by Joachim-Lebrun** [comment]
eip-review-bot changed the PR name unfortunately... I guess it is logical considering the fact i try to modify EIP-1. 
The correct title for this PR would be : **Introduction of ERC-1: Ethereum Request for Comments Process**

**Comment by Pandapip1** [comment]
Not sure why it's autodetecting it as website. Debugging now...

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Comment by Pandapip1** [comment]
@eth-bot rerun

**Pull request closed without merging**
