### PR TITLE
CI: Update jekyll-label-bot.yml

### PR DESCRIPTION
**Pull request by SamWilsn**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by lightclient** [comment]
looks like it still fails? or is that expected?

**Comment by nishuzumi** [comment]
The old version is still used before the merge, which should be observed after the merge

**Comment by Magken91** [comment]
Thank you

**Review by Skandiakiwi13 — APPROVED** [review]
It's a lot to take in all at once

**Comment by Skandiakiwi13** [comment]
Couldn't get 1 pull request

**Comment by Skandiakiwi13** [comment]
If is B when together. I find the wrap around lines difficult personally. Fi is B and 1 and 0 is 10 or 01. I do see the n-2 is 3

**Comment by Skandiakiwi13** [comment]
Fi in 1 . . 0 easy because makes 6

**Pull request merged**
