### PR TITLE
Add ERC: Cross-L2-Call Specification

### PR DESCRIPTION
**Pull request by wilsoncusack**
When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by abcoathup** [comment]
@wilsoncusack perhaps this should be a Rollup Improvement Proposal (RIP)?
https://github.com/ethereum/RIPs

Also, RollCall is a regular meeting to discuss L2 standards: https://github.com/ethereum/pm/issues/1099

**Comment by CarlBeek** [comment]
Agree with @abcoathup here, this should be a RIP.

**Comment by wilsoncusack** [comment]
Makes sense to me @CarlBeek @abcoathup ! Or maybe an RRP :D

**Comment by wilsoncusack** [comment]
https://github.com/ethereum/RIPs/pull/31

**Pull request closed without merging**
