### PR TITLE
Update ERC-3009: Move to Draft

### PR DESCRIPTION
**Pull request by dongri**
There is an error in signature verification with the current sample code.
```
EIP3009: invalid signature
```

It is necessary to change the order of `bytes32(chainId)` and `address(this)` to comply with `keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)")`.

### CODE REVIEW

**Comment by dongri** [comment]
Isn't anyone going to review it?

**Review by SamWilsn — APPROVED** [review]
I can approve this as an Editor, but you'll need to wait for one of the proposal authors to approve the pull request before it is merged.

Alternatively, if you'd like to champion this proposal, you can copy the text into a new proposal (adding yourself as an author) pull request.

**Comment by dongri** [comment]
> I can approve this as an Editor, but you'll need to wait for one of the proposal authors to approve the pull request before it is merged.
> 
> Alternatively, if you'd like to champion this proposal, you can copy the text into a new proposal (adding yourself as an author) pull request.

@SamWilsn Thank you for your review.
When submitting a pull request with a new proposal, do I need to change the EIP number? Should it be +1 from the latest EIP?

**Comment by dongri** [comment]
@SamWilsn https://github.com/ethereum/EIPs/pull/8819

**Comment by abcoathup** [comment]
@dongri to create a new ERC please create the PR in the ERC repo.  An ERC number will be manually assigned by an editor/associate.

**Review by Jcpayvoice23 — COMMENTED** [review]
We make a better marketing world

**Pull request closed without merging**
